name: RunLabel

on:
  pull_request:
    types: [closed]
jobs:
  RunLabel:
    runs-on: ubuntu-latest

    if: (github.event.pull_request.merged == true &&  contains(github.event.pull_request.labels.*.name, 'runAction'))

    steps:
      - run: echo "Hello World!"